management:
   endpoints:
      web.base-path:  /
server:
   port: 8181
spring:
   application:
      name: graphql
   datasource:
      driverClassName: org.h2.Driver
      password: ''
      url: jdbc:h2:mem:soumyadb
      username: sa
   h2:
      console:
         enabled: true
         path: /h2
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: update
      show-sql: true
   data:
      jpa:
         repository:
            bootstrap-mode: default